import { StyleSheet } from 'react-native';

// This branded splash uses its own dark/purple palette (literal values preserved).
export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#000',
  },
  blackBase: {
    flex: 1,
  },
  gridOverlay: {
    ...StyleSheet.absoluteFillObject,
    flexDirection: 'row',
    justifyContent: 'space-around',
    opacity: 0.04,
  },
  gridLine: {
    width: 1,
    height: '100%',
    backgroundColor: '#C4B5FD',
  },
  noiseDot: {
    position: 'absolute',
    borderRadius: 4,
    backgroundColor: '#C4B5FD',
  },
  centerContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 40,
  },
  glowHalo: {
    position: 'absolute',
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: 'transparent',
    shadowColor: '#7C3AED',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 80,
    elevation: 0,
    borderWidth: 0,
  },
  logoWrapper: {
    width: 180,
    height: 180,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#A78BFA',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.9,
    shadowRadius: 40,
    elevation: 20,
  },
  logoImage: {
    width: 140,
    height: 140,
  },
  lightSweep: {
    position: 'absolute',
    top: -20,
    left: -40,
    width: 60,
    height: 220,
    borderRadius: 30,
    backgroundColor: 'rgba(255,255,255,0.18)',
    transform: [{ rotate: '20deg' }],
    zIndex: 10,
  },
  appName: {
    fontSize: 42,
    fontWeight: '300',
    letterSpacing: 3,
    color: '#EDE9FE',
    fontFamily: 'System', // Replace with 'DM Sans' or 'Outfit' via expo-font
    textAlign: 'center',
  },
  appNameAccent: {
    fontWeight: '700',
    color: '#FFFFFF',
  },
  tagline: {
    fontSize: 13.5,
    fontWeight: '400',
    letterSpacing: 0.8,
    color: '#A78BFA',
    textAlign: 'center',
    lineHeight: 20,
    fontFamily: 'System',
    opacity: 0.9,
  },
  aiBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 24,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(167,139,250,0.3)',
    backgroundColor: 'rgba(124,58,237,0.12)',
    gap: 7,
  },
  aiBadgeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#A78BFA',
    shadowColor: '#A78BFA',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 4,
  },
  aiBadgeText: {
    fontSize: 11,
    fontWeight: '500',
    letterSpacing: 1.2,
    color: '#C4B5FD',
    textTransform: 'uppercase',
    fontFamily: 'System',
  },
  bottomMark: {
    position: 'absolute',
    bottom: 48,
    left: 0,
    right: 0,
    alignItems: 'center',
  },
  bottomMarkText: {
    fontSize: 9,
    fontWeight: '500',
    letterSpacing: 3.5,
    color: 'rgba(167,139,250,0.4)',
    textTransform: 'uppercase',
    fontFamily: 'System',
  },
});

export default styles;
