import { StyleSheet } from "react-native";
import { COLORS } from "../theme";

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: COLORS.bg },
  briefWrap: { paddingHorizontal: 16, marginTop: 6 },

  pillRow: { paddingHorizontal: 16, gap: 8, paddingBottom: 4 },
  pill: {
    paddingHorizontal: 18,
    paddingVertical: 8,
    borderRadius: 99,
    backgroundColor: "#efebff",
  },
  pillActive: { backgroundColor: COLORS.primary },
  pillText: { fontSize: 12, fontWeight: "700", color: "#464554" },
  pillTextActive: { color: "#fff" },

  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  sectionTitle: { fontSize: 17, fontWeight: "700", color: "#181445" },

  prioritySection: { marginTop: 24, paddingHorizontal: 16 },
  priorityGrid: { gap: 12 },
  priorityCard: {
    backgroundColor: "rgba(255,255,255,0.85)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.3)",
    borderLeftWidth: 4,
    padding: 16,
    shadowColor: "#6366f1",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  priorityTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  priorityBadge: { borderRadius: 99, paddingHorizontal: 10, paddingVertical: 3 },
  priorityBadgeText: { fontSize: 9, fontWeight: "700", letterSpacing: 0.6 },
  priorityDiffRow: { flexDirection: "row", alignItems: "center", gap: 3 },
  priorityDiffText: {
    fontSize: 9,
    fontWeight: "700",
    color: "#464554",
    letterSpacing: 0.5,
  },
  priorityTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#181445",
    marginBottom: 3,
  },
  prioritySubject: { fontSize: 12, color: "#464554", fontWeight: "400" },
  priorityFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 16,
  },
  priorityDueRow: { flexDirection: "row", alignItems: "center", gap: 5 },
  priorityDueText: { fontSize: 11, fontWeight: "700", color: "#464554" },

  progressWrap: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  progressText: { fontSize: 8, fontWeight: "800", color: "#111827" },

  completedSection: { marginTop: 24, paddingHorizontal: 16 },
  completedCard: {
    backgroundColor: "rgba(255,255,255,0.85)",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(199,196,215,0.3)",
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 10,
    shadowColor: "#6366f1",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 1,
  },
  completedIconBox: {
    width: 46,
    height: 46,
    borderRadius: 12,
    backgroundColor: "#ede9fe",
    alignItems: "center",
    justifyContent: "center",
  },
  completedTitle: { fontSize: 14, fontWeight: "700", color: "#181445" },
  completedMeta: {
    fontSize: 10,
    fontWeight: "700",
    color: "#767586",
    letterSpacing: 0.4,
    marginTop: 2,
  },
  completedChevron: { padding: 4 },

  taskCard: {
    marginHorizontal: 16,
    marginBottom: 10,
    backgroundColor: "rgba(255,255,255,0.85)",
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: "rgba(199,196,215,0.4)",
    borderLeftWidth: 4,
    position: "relative",
    shadowColor: "#6366f1",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 1,
  },
  updateDot: {
    position: "absolute",
    top: 10,
    right: 10,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.primary,
    borderWidth: 1.5,
    borderColor: "#fff",
  },
  taskTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  taskTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#181445",
    flex: 1,
    marginRight: 8,
  },
  taskBadge: {
    borderRadius: 99,
    paddingHorizontal: 8,
    paddingVertical: 3,
    alignSelf: "flex-start",
  },
  taskBadgeText: { fontSize: 10, fontWeight: "600" },
  taskMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 2,
  },
  taskMeta: { fontSize: 12, color: "#767586" },
  taskFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#e9e5ff",
    paddingTop: 8,
  },
  taskGraded: { fontSize: 12, color: "#15803d", fontWeight: "600" },
  taskMarks: { fontWeight: "700", color: "#111" },
  taskDone: { fontSize: 11, color: "#15803d", fontWeight: "600" },
  taskPending: { fontSize: 11, color: "#d97706" },

  emptyState: { alignItems: "center", marginTop: 40, gap: 8 },
  emptyText: {
    textAlign: "center",
    color: COLORS.textTertiary,
    fontSize: 13,
  },
});

export default styles;
